# Generated by Django 2.2.3 on 2019-08-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
