# Generated by Django 2.2.3 on 2019-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_delete_booklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLibraryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
