# Generated by Django 2.2.3 on 2019-08-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='BookID',
        ),
        migrations.AddField(
            model_name='userlist',
            name='BookID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.MyLibraryList'),
        ),
    ]
