# Generated by Django 2.2.3 on 2019-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190806_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylibrarylist',
            name='bling',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
